In [1]:
import numpy as np

In [2]:
x=[1,2,3]          # python array
y=np.array(x)      # numpy array
y=y*10
y

array([10, 20, 30])

In [3]:
y[1]     # accessing an element of an array

20

In [4]:
y[1]=100
y

array([ 10, 100,  30])

In [5]:
y[-3]=2
y

array([  2, 100,  30])

In [6]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

### <font color=magenta>zeros, ones</font>

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [11]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

### <font color=magenta> multidimensional arrays </font>

In [12]:
m=np.ones([2,3,4])  # two groups, three rows and four columns
m

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
m.size    # The size of m=2*3*4

24

In [14]:
m.dtype

dtype('float64')

In [15]:
m.shape

(2, 3, 4)

### <font color=red> shape </font>

In [16]:
a=np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
a.shape=(2,5)
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [18]:
a[1][2]

8.0

### <font color=red> Boolean mask </font>

In [19]:
x=np.array([1,2,3])
y=np.array([True,False,True])
x[y]

array([1, 3])

In [20]:
y.shape

(3,)

#### <font color=red>numpy inner and dot product</font>

In [21]:
left=np.arange(6).reshape((2,3))
right=np.arange(15).reshape((3,5))
np.inner(left,right)

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [22]:
np.dot(left,right)   #dot=matrix(2*3)xmatrix(3*5)=matrix(2*5)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [23]:
s=np.dot(left,right)
s.sum()

625

### <font color=red> Append </font>

In [24]:
a=np.array(np.arange(24)).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [25]:
b=np.append(a,[5,6,7,8])

In [26]:
b.shape

(28,)

In [27]:
b.reshape((7,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [28]:
c=np.array(np.arange(24)).reshape(2,3,4)*10+3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [29]:
np.append(a,c, axis=0)    # (2,3,4)+(2,3,4)=(4,3,4)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [30]:
np.append(a,c,axis=1)  # (2,3,4)+(2,3,4)=(2,6,4)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [31]:
d=np.hstack((a,c))
d

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [32]:
d.shape

(2, 6, 4)

In [33]:
d[0,0,2]=999
d

array([[[  0,   1, 999,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [34]:
np.insert(d,1,444,axis=0)

array([[[  0,   1, 999,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [35]:
np.insert(d,1,444,axis=1)

array([[[  0,   1, 999,   3],
        [444, 444, 444, 444],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [444, 444, 444, 444],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [36]:
np.insert(d,1,444,axis=2)

array([[[  0, 444,   1, 999,   3],
        [  4, 444,   5,   6,   7],
        [  8, 444,   9,  10,  11],
        [  3, 444,  13,  23,  33],
        [ 43, 444,  53,  63,  73],
        [ 83, 444,  93, 103, 113]],

       [[ 12, 444,  13,  14,  15],
        [ 16, 444,  17,  18,  19],
        [ 20, 444,  21,  22,  23],
        [123, 444, 133, 143, 153],
        [163, 444, 173, 183, 193],
        [203, 444, 213, 223, 233]]])

### <font color=red> Delete </font>

In [37]:
e=np.empty(c.shape)
np.copyto(e,c)
e

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [163., 173., 183., 193.],
        [203., 213., 223., 233.]]])

In [38]:
np.delete(e,1,axis=0)

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]]])

In [39]:
np.delete(e,1,axis=1)

array([[[  3.,  13.,  23.,  33.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [203., 213., 223., 233.]]])

In [40]:
np.delete(e,1,axis=2)

array([[[  3.,  23.,  33.],
        [ 43.,  63.,  73.],
        [ 83., 103., 113.]],

       [[123., 143., 153.],
        [163., 183., 193.],
        [203., 223., 233.]]])

### <font color=red> Rearanging array elements

In [41]:
x=np.array(np.arange(24))
x38=x.reshape((3,8))
x234=x.reshape((2,3,4))

In [42]:
x38

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [43]:
y1=np.fliplr(x38)      #flip right left
y1

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [44]:
x234

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [45]:
y2=np.fliplr(x234)
y2

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [46]:
y3=np.flipud(x38)
y3

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [47]:
y4=np.flipud(x234)
y4

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [48]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

1. Use np transpose to permute all the axes at once
2. Use np seapaxes to seap any two axes
3. Use np rollaxis to rotate the axes

In [49]:
y5=np.roll(x,7)
y5

array([17, 18, 19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14, 15, 16])

In [50]:
y6=np.roll(x,-7)
y6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        0,  1,  2,  3,  4,  5,  6])

In [51]:
y7=np.rot90(x38)   #rotate CCW
y7

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [52]:
y8=np.rot90(x38,k=-1)   #rotate CCW
y8

array([[16,  8,  0],
       [17,  9,  1],
       [18, 10,  2],
       [19, 11,  3],
       [20, 12,  4],
       [21, 13,  5],
       [22, 14,  6],
       [23, 15,  7]])

In [53]:
x=np.array(np.arange(24))
x38=x.reshape((3,8))
x234=x.reshape((2,3,4))

In [54]:
y1=np.transpose(x)
y1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
y2=np.transpose(x38)
y2

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [56]:
y3=np.transpose(x234,axes=(0,2,1))
y3

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [57]:
y4=np.swapaxes(x234,1,0)
y4

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [58]:
y5=np.rollaxis(x234,0,2)
y5

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [59]:
a = np.array([0, 1, 2])     #  1*2
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [60]:
np.tile(a, (2, 2))          #  2*2

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [61]:
np.tile(a, (2, 1, 2))       # 2*1*2

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

### <font color=red> Linear Algebra </font>

In [62]:
B=np.matrix([[11],[22],[33]])
B

matrix([[11],
        [22],
        [33]])

In [63]:
A=np.matrix([[3,1,4],[1,5,9],[2,6,5]])
A

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [64]:
AT=A.T   #tranpose of marix
AT

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [65]:
AI=A.I    #inverse of matrix
AI

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [66]:
y4=np.eye(4)
y4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### <font color=green> Solving simultaneous linear equations using inverse which is non-efficient</font> 
### <font color=green> if AX=B then X=AI*B </font>

In [67]:
X=AI*B
X

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

### <font color=green> Solving simultaneous linear equations using efficient method</font> 

In [68]:
from numpy.linalg import solve
solve(A,B)

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

### <font color=green> Finding eigen values and eigen vectors</font> 

In [69]:
from numpy.linalg import eig
eig(A)

(array([13.08576474,  2.58000566, -2.66577041]),
 matrix([[-0.31542644, -0.95117074, -0.32372474],
         [-0.72306109,  0.30781323, -0.70222933],
         [-0.61456393,  0.02291827,  0.63409484]]))

In [72]:
np.__version__

'1.15.1'

In [79]:
a=np.arange(10)    # reverse order
b=a[::-1]
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [80]:
b=a*3
b

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [87]:
z=np.zeros(20)   #create array with 20 zeros; every fifth element equal four
z[0::5]=4
z

array([4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0.,
       0., 0., 0.])

In [89]:
I=np.identity(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [91]:
I=np.eye(5,dtype='int')    #all elements of the I-matrix are integer
I

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [92]:
I=np.asmatrix(np.eye(5,dtype='int'))    #all elements of the I-matrix are integer
I

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [96]:
r=np.random.random(30)
r.mean()

0.5209959825665065

#### <font color=red> Create an 8x8 checker board with alternating zeros and ones

In [135]:
c=np.zeros((8,8),dtype=int)
c[1::2,::2]=1     # 1::2 means every other element in row starting at index=1; the same concept for column
c[::2,1::2]=1
c

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### <font color=red> Array Slicing: Accessing Subarrays </font>
##### https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html

#### <font color=red> 1. One Dimentional Subarrays </font>

In [123]:
m=np.arange(10)
m[:5]

array([0, 1, 2, 3, 4])

In [124]:
m[5:]

array([5, 6, 7, 8, 9])

In [125]:
m[4:7]

array([4, 5, 6])

In [134]:
m[::2]   # every other elements starting at index=0

array([0, 2, 4, 6, 8])

In [127]:
m[1::2]   # every other elements, starting at index 1

array([1, 3, 5, 7, 9])

In [128]:
m[::-1]    # reveresed every other element, starting from index=0     minus sign means reverese

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [129]:
m[5::-2]    # reveresed every other from index=5

array([5, 3, 1])

#### <font color=red> 2. Multi Dimentional Subarrays </font>

In [130]:
n=np.array([[1,2,3,4],
             [5,6,7,8],
            [9,10,11,12]])
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [131]:
n[:2,:3]    #two rows, three columns

array([[1, 2, 3],
       [5, 6, 7]])

In [132]:
n[:3,::2]    # three rows, every other column

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [133]:
n[::-1,::-1]     # minus means reverese

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

#### <font color=red> Create a sorted vector with 'n' random numbers </font>

In [146]:
r=np.random.random(10)
r

array([0.37657112, 0.76386242, 0.35970551, 0.67897279, 0.02963619,
       0.56874275, 0.17385252, 0.00848705, 0.31622547, 0.53876591])

In [147]:
r.sort()
r

array([0.00848705, 0.02963619, 0.17385252, 0.31622547, 0.35970551,
       0.37657112, 0.53876591, 0.56874275, 0.67897279, 0.76386242])

#### <font color=red> replace largest element in random array with the value 1234 without sorting </font>

In [159]:
m=np.random.random(10)
m[m.argmax()]=6.6666
m

array([0.45295244, 0.34146056, 0.10107119, 0.26282389, 0.51446946,
       0.62749188, 0.75979197, 6.6666    , 0.48219945, 0.74686912])

#### <font color=red> Making an array read-only (immutable) </font>

In [163]:
q=np.array(np.arange(10))
q.flags.writeable=False    # a new element cannot be assigned to q